### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by Morozov-5F** [Morozov-5F/monoflash-planes-game#1]
- [x] Параллакс в уровнях
- [x] Смена уровней (по инициативе хоста) 
- [ ] Попадания 
- [x] Имена игроков без хитбоксов
- [ ] Интерполяция
- [ ] Отсоединение игроков
- [ ] Скроллящийся список
- [ ] Фильтрация уже играющих хостов
